# Generated by Django 5.2.4 on 2025-08-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangouts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='biografia',
        ),
        migrations.AlterField(
            model_name='profile',
            name='fecha_ingreso',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
